//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Transcore.TagInventory.BusinessLogic {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Transcore.TagInventory.BusinessLogic.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE dbDTS
        ///Go
        ///
        ///BEGIN TRY
        ///
        ///BEGIN TRAN
        ///
        ///
        ///DECLARE
        ///	@ipv_iUpdUserID INT,
        ///	@ipv_dcCostPerTag DECIMAL(9, 3),
        ///	@dtGetDate DATETIME
        ///
        ///SELECT
        ///	@ipv_iUpdUserID = 152227,
        ///	@ipv_dcCostPerTag = 33.057,
        ///	@dtGetDate = GetDate()
        ///
        ///IF NOT EXISTS (SELECT 0 FROM dbo.tbUser WITH (NOLOCK) WHERE iUpdUserID = @ipv_iUpdUserID)
        ///BEGIN
        ///	RAISERROR(&apos;Kindly use your own UserID to run the script.&apos;, 14, 1)
        ///	RETURN
        ///END
        ///
        ///IF (@ipv_dcCostPerTag IS NULL)
        ///BEGIN
        ///	RAISERROR(&apos;Kindly set cost per tag in @ipv_dcCostPerTag para [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CostTagsScript {
            get {
                return ResourceManager.GetString("CostTagsScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE dbDTS
        ///Go
        ///
        ///BEGIN TRY
        ///
        ///BEGIN TRAN
        ///
        ///
        ///DECLARE
        ///	@ipv_iUpdUserID INT,
        ///	@ipv_dcCostPerTag DECIMAL(9, 3),
        ///	@dtGetDate DATETIME
        ///
        ///SELECT
        ///	@ipv_iUpdUserID = 152227,
        ///	@ipv_dcCostPerTag = 0,
        ///	@dtGetDate = GetDate()
        ///
        ///IF NOT EXISTS (SELECT 0 FROM dbo.tbUser WITH (NOLOCK) WHERE iUpdUserID = @ipv_iUpdUserID)
        ///BEGIN
        ///	RAISERROR(&apos;Kindly use your own UserID to run the script.&apos;, 14, 1)
        ///	RETURN
        ///END
        ///
        ///IF (@ipv_dcCostPerTag IS NULL)
        ///BEGIN
        ///	RAISERROR(&apos;Kindly set cost per tag in @ipv_dcCostPerTag parameter [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NoCostTagsScript {
            get {
                return ResourceManager.GetString("NoCostTagsScript", resourceCulture);
            }
        }
    }
}
